create table public.m_user_answers (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp with time zone null,
  answer_1 text not null,
  answer_2 text not null,
  questionaire_id bigint null,
  auth_user_id uuid null,
  device_id character varying(36) null,
  constraint m_user_answers_pkey primary key (id),
  constraint m_user_answers_auth_user_id_fkey foreign KEY (auth_user_id) references m_users (auth_user_id),
  constraint m_user_answers_questionaire_id_fkey foreign KEY (questionaire_id) references m_questions (id)
) TABLESPACE pg_default;

create index IF not exists idx_user_answers_device_id on public.m_user_answers using btree (device_id) TABLESPACE pg_default;

create table public.m_questions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  question_1 text null,
  question_2 text null,
  constraint m_users_question_pkey primary key (id)
) TABLESPACE pg_default;

create table public.m_devices (
  id serial not null,
  device_id character varying(36) not null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  constraint m_devices_pkey primary key (id),
  constraint m_devices_device_id_key unique (device_id)
) TABLESPACE pg_default;

create table public.m_users (
  id uuid not null default gen_random_uuid (),
  auth_user_id uuid not null,
  linkedin_id character varying(255) null,
  email character varying(255) not null,
  email_verified boolean null default false,
  name character varying(255) null,
  given_name character varying(255) null,
  family_name character varying(255) null,
  picture text null,
  locale character varying(10) null default 'en-US'::character varying,
  provider character varying(50) null default 'linkedin_oidc'::character varying,
  user_metadata jsonb null,
  app_metadata jsonb null,
  last_sign_in timestamp with time zone null,
  sign_in_count integer null default 1,
  is_active boolean null default true,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint m_users_pkey primary key (id),
  constraint m_users_auth_user_id_key unique (auth_user_id),
  constraint m_users_linkedin_id_key unique (linkedin_id),
  constraint m_users_auth_user_id_fkey foreign KEY (auth_user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger on_m_users_updated BEFORE
update on m_users for EACH row
execute FUNCTION handle_updated_at ();

create table public.m_users_posts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  auth_user_id uuid null,
  hook text null,
  post text null,
  updated_at timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  status smallint null default '0'::smallint,
  is_deleted boolean null default false,
  linkedin_post_id character varying(255) null,
  linkedin_post_url character varying(500) null,
  published_at timestamp without time zone null,
  sections jsonb null,
  topic text null,
  intention text null,
  device_id character varying(36) null,
  constraint m_users_posts_pkey primary key (id),
  constraint m_users_posts_auth_user_id_fkey foreign KEY (auth_user_id) references m_users (auth_user_id)
) TABLESPACE pg_default;

create index IF not exists idx_users_posts_device_id on public.m_users_posts using btree (device_id) TABLESPACE pg_default;

create index IF not exists idx_m_users_posts_linkedin_post_id on public.m_users_posts using btree (linkedin_post_id) TABLESPACE pg_default;