CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS public.m_post_memories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id character varying(36) NOT NULL,
  post_id BIGINT NULL,
  source_type VARCHAR(20) NOT NULL DEFAULT 'post',
  source_status VARCHAR(20) NOT NULL DEFAULT 'draft',
  source_text TEXT NOT NULL,
  summary TEXT NOT NULL,
  inferred_intent TEXT NOT NULL,
  themes JSONB NOT NULL DEFAULT '[]'::jsonb,
  style_signals JSONB NOT NULL DEFAULT '{}'::jsonb,
  topic TEXT NULL,
  vector_document_id TEXT NOT NULL,
  embedding_state VARCHAR(20) NOT NULL DEFAULT 'pending',
  sync_status VARCHAR(50) NOT NULL DEFAULT 'pending',
  sync_version INTEGER NOT NULL DEFAULT 1,
  embedding_json JSONB NULL,
  embedding vector(1536) NULL,
  last_error TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT m_post_memories_device_post_key UNIQUE (device_id, post_id)
);

CREATE INDEX IF NOT EXISTS idx_post_memories_device_id
  ON public.m_post_memories (device_id);

CREATE INDEX IF NOT EXISTS idx_post_memories_sync_status
  ON public.m_post_memories (device_id, sync_status);

CREATE INDEX IF NOT EXISTS idx_post_memories_embedding
  ON public.m_post_memories
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

CREATE TABLE IF NOT EXISTS public.m_style_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id character varying(36) NOT NULL UNIQUE,
  summary TEXT NOT NULL,
  tone JSONB NOT NULL DEFAULT '[]'::jsonb,
  structure_habits JSONB NOT NULL DEFAULT '{}'::jsonb,
  cta_habits JSONB NOT NULL DEFAULT '{}'::jsonb,
  format_habits JSONB NOT NULL DEFAULT '{}'::jsonb,
  common_themes JSONB NOT NULL DEFAULT '[]'::jsonb,
  confidence_score NUMERIC(5,2) NOT NULL DEFAULT 0,
  sample_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_recomputed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.m_user_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id character varying(36) NOT NULL UNIQUE,
  preferred_tone TEXT NULL,
  target_audience TEXT NULL,
  preferred_formats JSONB NOT NULL DEFAULT '[]'::jsonb,
  cta_preference TEXT NULL,
  emoji_preference TEXT NULL,
  forbidden_phrases JSONB NOT NULL DEFAULT '[]'::jsonb,
  hard_constraints JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
